version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: deploy/docker/backend/Dockerfile
    image: botly/backend:latest
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn core.wsgi -b 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./src/static:/src/static:rw
      - ./src/media:/src/media:rw
      - ./src/logs:/src/logs:rw
    cap_add:
      - ALL

  db:
    build:
      context: .
      dockerfile: deploy/docker/postgres/Dockerfile
    image: botly/db:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    build:
      context: .
      dockerfile: deploy/docker/redis/Dockerfile
    image: botly/redis:latest
    restart: unless-stopped
    privileged: true
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
      - redis_conf:/conf
    expose:
      - 6379

volumes:
  redis_data:
  redis_conf:
  postgres_data:
