# Generated by Django 5.2b1 on 2025-09-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
