# Generated by Django 5.2b1 on 2025-09-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companybot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
    ]
