# Generated by Django 5.2b1 on 2025-09-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companybot_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Уникальное имя компании (например, ООО "Альфа")', max_length=255, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(help_text='Пользователь, создавший или управляющий этой компанией', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='_token',
            field=models.CharField(help_text='Telegram токен бота (хранится в зашифрованном виде)', max_length=255, verbose_name='Зашифрованный токен'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='bot_module',
            field=models.CharField(choices=[('FEEDBACK_BOT', 'Feedback Bot')], help_text='Назначение или функциональность бота (например, жалобы, опросы и т.д.)', max_length=255, verbose_name='Модуль бота'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='company',
            field=models.ForeignKey(help_text='Компания, к которой принадлежит бот', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='name',
            field=models.CharField(help_text='Человекочитаемое имя бота для отображения в интерфейсе', max_length=255, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='Обновлён'),
        ),
    ]
