# Generated by Django 5.2b1 on 2025-09-11 19:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbbSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_send_chat_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('start_text', models.TextField(default='', max_length=1000)),
                ('feedback_create_button_text', models.CharField(default='', max_length=50)),
                ('feedback_send_button_text', models.CharField(default='', max_length=50)),
                ('feedback_cancel_button_text', models.CharField(default='', max_length=50)),
                ('feedback_send_text', models.TextField(default='', max_length=1000)),
                ('allowed_message_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TEXT', 'Text'), ('FILE', 'File'), ('VOICE', 'Voice'), ('VIDEO', 'Video'), ('VOICE_VIDEO', 'Voice Video')], max_length=50), default=list, size=None)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.companybot')),
            ],
            options={
                'db_table': 'feedback_bot__settings',
            },
        ),
        migrations.CreateModel(
            name='FbbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(db_index=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('nickname', models.CharField(max_length=60, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.companybot')),
            ],
            options={
                'db_table': 'feedback_bot__users',
                'unique_together': {('bot', 'tg_id')},
            },
        ),
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_message_id', models.CharField(max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('FILE', 'File'), ('VOICE', 'Voice'), ('VIDEO', 'Video'), ('VOICE_VIDEO', 'Voice Video')], max_length=11)),
                ('text', models.TextField()),
                ('file_id', models.CharField(max_length=255, null=True)),
                ('video_id', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback_bot.fbbuser')),
            ],
            options={
                'db_table': 'feedback_bot__users_feedback',
            },
        ),
    ]
