# Generated by Django 5.2b1 on 2025-09-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbbsettings',
            options={'verbose_name': 'Настройки бота', 'verbose_name_plural': 'Настройки бота'},
        ),
        migrations.AlterModelOptions(
            name='fbbuser',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='fbbsettings',
            old_name='feedback_send_button_text',
            new_name='feedback_button_text',
        ),
    ]
