# Generated by Django 5.2b1 on 2025-09-13 14:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_name_alter_company_owner_and_more'),
        ('feedback_bot', '0002_alter_fbbsettings_options_alter_fbbuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbbsettings',
            options={'verbose_name': 'Настройки бота', 'verbose_name_plural': 'Настройки ботов'},
        ),
        migrations.AlterModelOptions(
            name='fbbuser',
            options={'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='fbbsettings',
            name='feedback_button_text',
        ),
        migrations.RemoveField(
            model_name='fbbsettings',
            name='feedback_cancel_button_text',
        ),
        migrations.RemoveField(
            model_name='fbbsettings',
            name='feedback_create_button_text',
        ),
        migrations.RemoveField(
            model_name='fbbsettings',
            name='feedback_send_text',
        ),
        migrations.AddField(
            model_name='fbbsettings',
            name='cancel_button_text',
            field=models.CharField(default='❌ Отменить', help_text='Текст кнопки для отмены отзыва', max_length=50, verbose_name='Текст кнопки отмены'),
        ),
        migrations.AddField(
            model_name='fbbsettings',
            name='confirm_button_text',
            field=models.CharField(default='✅ Подтвердить', help_text='Текст кнопки для подтверждения отзыва', max_length=50, verbose_name='Текст кнопки подтверждения'),
        ),
        migrations.AddField(
            model_name='fbbsettings',
            name='feedback_cancel_text',
            field=models.TextField(default='Ваш отзыв отменён. Вы можете начать заново.', help_text='Ответ пользователю после отмены отзыва', max_length=1000, verbose_name='Текст после отмены'),
        ),
        migrations.AddField(
            model_name='fbbsettings',
            name='feedback_confirm_text',
            field=models.TextField(default='Спасибо! Ваше сообщение отправлено и будет рассмотрено.', help_text='Ответ пользователю после подтверждения отправки отзыва', max_length=1000, verbose_name='Текст после подтверждения'),
        ),
        migrations.AddField(
            model_name='fbbsettings',
            name='feedback_send_message',
            field=models.TextField(default='Ваш отзыв отправлен. Спасибо!', help_text='Сообщение пользователю после успешной отправки отзыва', max_length=1000, verbose_name='Текст при отправке отзыва'),
        ),
        migrations.AddField(
            model_name='fbbsettings',
            name='invalid_feedback_message_text',
            field=models.CharField(default='Вы ещё не отправили ни одного сообщения.', help_text='Сообщение, если пользователь нажал подтвердить без ввода данных', max_length=50, verbose_name='Текст при ошибке отправки отзыва'),
        ),
        migrations.AddField(
            model_name='fbbsettings',
            name='invalid_message_type_text',
            field=models.CharField(default='Неподдерживаемый тип сообщения.', help_text='Ответ пользователю, если он отправил запрещённый тип сообщения', max_length=50, verbose_name='Текст при недопустимом типе сообщения'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Если это ответ на другое сообщение — выберите родительское', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feedback_bot.userfeedback', verbose_name='Родительское сообщение'),
        ),
        migrations.AlterField(
            model_name='fbbsettings',
            name='allowed_message_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('document', 'Document'), ('photo', 'Photo'), ('video', 'Video'), ('video_note', 'Video Note'), ('voice', 'Voice')], max_length=50), default=list, help_text='Выберите, какие типы сообщений разрешено отправлять (текст, фото, видео и т.д.)', size=None, verbose_name='Разрешённые типы сообщений'),
        ),
        migrations.AlterField(
            model_name='fbbsettings',
            name='bot',
            field=models.ForeignKey(help_text='Выберите бота, к которому относятся эти настройки', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.companybot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='fbbsettings',
            name='feedback_send_chat_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='Введите chat_id через запятую, куда будут отправляться отзывы', size=None, verbose_name='Чаты для уведомлений'),
        ),
        migrations.AlterField(
            model_name='fbbsettings',
            name='start_text',
            field=models.TextField(default='Здравствуйте! Оставьте, пожалуйста, жалобу или предложение.', help_text='Сообщение, которое бот отправляет пользователю после команды /start', max_length=1000, verbose_name='Текст приветствия'),
        ),
        migrations.AlterField(
            model_name='fbbuser',
            name='bot',
            field=models.ForeignKey(help_text='Бот, в котором зарегистрирован пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.companybot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='fbbuser',
            name='first_name',
            field=models.CharField(help_text='Имя пользователя, полученное из Telegram', max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='fbbuser',
            name='last_name',
            field=models.CharField(help_text='Фамилия пользователя, полученная из Telegram', max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='fbbuser',
            name='nickname',
            field=models.CharField(help_text='Username (никнейм) пользователя в Telegram', max_length=60, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='fbbuser',
            name='phone',
            field=models.CharField(help_text='Телефон пользователя, если был предоставлен', max_length=13, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='fbbuser',
            name='tg_id',
            field=models.BigIntegerField(db_index=True, help_text='Уникальный идентификатор пользователя в Telegram', verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='file_id',
            field=models.CharField(blank=True, help_text='file_id вложения (фото, документ и т.д.), если есть', max_length=255, null=True, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('document', 'Document'), ('photo', 'Photo'), ('video', 'Video'), ('video_note', 'Video Note'), ('voice', 'Voice')], help_text='Тип содержимого отзыва (текст, фото, видео и т.д.)', max_length=11, verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='text',
            field=models.TextField(help_text='Текст сообщения пользователя (если есть)', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='tg_message_id',
            field=models.CharField(help_text='ID сообщения в Telegram, если доступен', max_length=255, null=True, verbose_name='ID сообщения в Telegram'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, отправивший отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback_bot.fbbuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='video_id',
            field=models.CharField(blank=True, help_text='video_id видео, если есть', max_length=255, null=True, verbose_name='Video ID'),
        ),
    ]
