# Generated by Django 5.2b1 on 2025-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_bot', '0003_alter_fbbsettings_options_alter_fbbuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='video_id',
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='file_id',
            field=models.CharField(blank=True, help_text='file_id вложения (фото, видео, документ и т.д.), если есть', max_length=255, null=True, verbose_name='File ID'),
        ),
    ]
