# Generated by Django 5.2b1 on 2025-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_bot', '0004_remove_userfeedback_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbbsettings',
            name='feedback_send_message',
            field=models.TextField(default='Хотите добавить ещё сообщение? Просто отправьте его. Готовы отправить отзыв? Нажмите ✅ Подтвердить или ❌ Отменить.', help_text='Сообщение пользователю после успешной отправки отзыва', max_length=1000, verbose_name='Текст при отправке отзыва'),
        ),
    ]
